### PR TITLE
update model download folder to .cache and rewrite model download logic.

### PR DESCRIPTION
**Pull request by venkata-ramireddy-mettu**

### CODE REVIEW

**Comment by swapaj** [comment]
@venkata-ramireddy-mettu Did we test the code ?? All models to be tested wherever the model_path comes.

**Comment by swapaj** [comment]
@venkata-ramireddy-mettu there are 5 sub-modules in NLP modules. All needs to changed.

**Comment by venkata-ramireddy-mettu** [comment]
Yes Swapnil all changes are tested.

**Comment by venkata-ramireddy-mettu** [comment]
> @venkata-ramireddy-mettu there are 5 sub-modules in NLP modules. All needs to changed.

I updated for remaining two models as well.

**Comment by venkata-ramireddy-mettu** [comment]
> @venkata-ramireddy-mettu Did we test the code ?? All models to be tested wherever the model_path comes.

Yes. All changes are tested.

**Pull request closed without merging**
